version: '3.8'
services:
  db_courses:
    image: postgres:14.1
#    build:
#      context: ./db_courses
#      dockerfile: Dockerfile
    container_name: db_courses
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5434:5432'
  db_users:
    image: postgres:14.1
#    build:
#      context: ./db_users
#      dockerfile: Dockerfile
    container_name: db_users
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  auth:
    image: auth-service
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      - db_users
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_users:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8081:8081'
  api:
    image: maven:3.8.1-adoptopenjdk-11
    build: .
    container_name: api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_courses:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'

  code-runner:
    image: coder-runner-service
    build:
      context: .
      dockerfile: ./code-runner-service/Dockerfile
    container_name: code-runner-service
    ports:
      - '8082:8082'




#networks:
#  micro-service-network:
#
#volumes:
#  database_data:
#    driver: local